# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=80, unique=True)),
                ('nombre', models.IntegerField(max_length=100)),
                ('apellidos', models.IntegerField(max_length=100)),
                ('email', models.EmailField(help_text='un correo electronico valido por favor', max_length=100)),
                ('celular', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField(max_length=50)),
                ('precio', models.IntegerField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.IntegerField(max_length=50, unique=True)),
                ('celular', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_venta', models.IntegerField(max_length=50)),
                ('valor', models.IntegerField(max_length=80)),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
