# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20170510_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad_venta',
            field=models.IntegerField(),
        ),
    ]
